### ISSUE TITLE
shader not working

### ISSUE THREAD

**Issue by district10** [stemkoski/three.py#4]
When running examples, I got this error message:

```
`in' qualifier in declaration of `vColor' only valid for function parameters in GLSL 1.10
```

I googled around and found that I need something like `#version core 330`. So I modified OpenGLUtils.py:

```diff
diff --git a/three.py/core/OpenGLUtils.py b/three.py/core/OpenGLUtils.py
index c4c9cfb..09049b4 100644
--- a/three.py/core/OpenGLUtils.py
+++ b/three.py/core/OpenGLUtils.py
@@ -7,7 +7,8 @@ class OpenGLUtils(object):
 
     @staticmethod
     def initializeShader(shaderCode, shaderType):
-    
+        shaderCode = '#version 130\n' + shaderCode
+
         # create empty shader object and return reference value
```

The 'in qualifier not valid' error is gone, but I got 'error: C-style initialization requires the GL_ARB_shading_language_420pack extension'...

Seems the shader is not compatible with my laptop (Lenovo ThinkPad X1 Carbon 5th Gen, GPU: Intel Corporation HD Graphics 620, OS: ubuntu 16.04). Is there any solution? Will three.py be more compatible?

Thank you.

**Comment by Michael-Pascale** [comment]
Hello!

What demo were you trying to run?
The shaders are written within the materials folder so you could see the shaders in detail within the material files.

**Comment by stemkoski** [comment]
Since I'm not sure what version of GLSL your hardware supports, I'm going to take a guess. 
In older versions of GLSL:

- instead of "in" variables in a vertex shader, they were "attribute" variables
- instead of "out" variables in a vertex shader, they were "varying" variables
- instead of "in" variables in a fragment shader, they were (also) "varying" variables

Try changing the "in" and "out" qualifiers in this way, and let us know if the shaders work on your system then.

**Comment by district10** [comment]
@Michael-Pascale @stemkoski  I did that, I removed these 'in' 'out' qualifiers but other errors came in.

> GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

I googled a bit more and found a solution in <http://developer.download.nvidia.com/opengl/specs/GL_ARB_shading_language_420pack.txt>

This fix my problem:

```diff
diff --git a/three.py/core/OpenGLUtils.py b/three.py/core/OpenGLUtils.py
index c4c9cfb..5839c61 100644
--- a/three.py/core/OpenGLUtils.py
+++ b/three.py/core/OpenGLUtils.py
@@ -7,7 +7,9 @@ class OpenGLUtils(object):
 
     @staticmethod
     def initializeShader(shaderCode, shaderType):
+        extension = '#extension GL_ARB_shading_language_420pack : require\n'
+        shaderCode = '#version 130\n' + extension + shaderCode
```

And it works now
![image](https://user-images.githubusercontent.com/5262037/55687009-9455d700-599a-11e9-9bf8-59b399586d9f.png)

Thank you both. Thanks a lot, This project is helpful. :smiley:

**Comment by district10** [comment]
By the way, I used to export THREE.js model as json file (spec: <https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4>) so I can load it in https://threejs.org/editor/, it's a helpful online tool for debugging my 3d map (HD Map for autonomous driving).

It will be great to if you can export the model and load in THREE.js online editor.
:laughing: Just a feature request. Thank you again.

**Comment by lukestanley** [comment]
I had the same issue, and I applied the fix in this PR:
https://github.com/stemkoski/three.py/pull/10
